version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/deploy/build
    overwrite: yes
    file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user
      environment:
        MODULES: $(git diff --name-only $DEPLOYMENT_BASE_REVISION $DEPLOYMENT_TARGET_BRANCH | awk -F/ '{ print $1 }' | uniq)
