version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy/verby-api-server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh verby-api-server
      timeout: 60
      runas: ec2-user