spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${VERBY_MAIN_URL}/verby_main?serverTimezone=Asia/Seoul
    username: ${VERBY_MAIN_USERNAME}
    password: ${VERBY_MAIN_PASSWORD}

  redis:
    host: ${VERBY_AUTH_HOST}
    port: ${VERBY_AUTH_PORT}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY_ID}       # AWS IAM AccessKey 적기
      secretKey: ${S3_SECRET_ACCESS_KEY}   # AWS IAM SecretKey 적기
    s3:
      bucket: verby-deploy
      directoriess:
        songs:
          images: static/song/image
    region:
      static: ap-northeast-2
    stack:
      auto: false