spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 100MB

  session:
    store-type: redis
    redis:
      flush-mode: on-save

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect

static:
  paths:
    song:
      image: static/song/images