spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8341/verby_main?serverTimezone=Asia/Seoul
    username: root
    password: root

  redis:
    host: localhost
    port: 8342

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: INFO