spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${VERBY_MAIN_URL}/verby_main?serverTimezone=Asia/Seoul
    username: ${VERBY_MAIN_USERNAME}
    password: ${VERBY_MAIN_PASSWORD}e

infra:
  main-redis:
    host: ${VERBY_CACHE_HOST}
    port: ${VERBY_CACHE_PORT}