spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8341/verby_main?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY_ID}       # AWS IAM AccessKey 적기
      secretKey: ${S3_SECRET_ACCESS_KEY}   # AWS IAM SecretKey 적기
    s3:
      bucket: verby-deploy
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    root: INFO
    com.amazonaws.util.EC2MetadataUtils: error

infra:
  auth-redis:
    host: localhost
    port: 8342

  main-redis:
    host: localhost
    port: 8342